load('20210605_04.mat');

hysterisis = 0;5;15;			% hysterisis for marking the end of a saccade (ms)
minDur = 15;				% minimal duration of a saccade (ms)
minInterval = 50;15;			% minimal duration of a saccade, any event happens less than this after a detected saccade will be ignored (ms)
devThresh = 5;			% threshold for deviation (arcmin)
refWindow = 20;30;			% reference window for saccade detection (ms)
refInterval = 1;3;

[isSacOn, isBlinking, isNoTracking, deviation] = main(...
														double(eis_data.eye_data.eye_1.calibrated_x),...
														double(eis_data.eye_data.eye_1.calibrated_y),...
														logical(eis_data.eye_data.eye_1.blinking),...
														logical(eis_data.eye_data.eye_1.tracking),...
														int32(eis_data.eye_data.timing.spd),...
														single(hysterisis),...
														single(minDur),...
														single(minInterval),...
														single(devThresh),...
														single(refWindow),...
														single(refInterval)...
												);

figure; hold on;
plot(eis_data.eye_data.eye_1.calibrated_x, 'b');
plot(eis_data.eye_data.eye_1.calibrated_y, 'r');

idx = cumsum(eis_data.eye_data.timing.spd);
x = eis_data.eye_data.eye_1.calibrated_x(idx);
y = eis_data.eye_data.eye_1.calibrated_y(idx);
plot(idx(isSacOn), x(isSacOn), 'k.');
plot(idx(isSacOn), y(isSacOn), 'k.');
plot(idx, deviation*100, 'k');
plot(xlim, [100 100]*devThresh, 'k--');